version: '3.9'

volumes:
  postgresql_data:

services:
  postgresql:
    image: postgres:16.1-alpine
    container_name: kc_db
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      keycloak:

  keycloak:
    image: bitnami/keycloak:22.0.5
    container_name: kc_server
    restart: unless-stopped
    depends_on:
      - postgresql
    environment:
      # - KC_HTTP_ENABLED=true
      # - DB=keycloak
      # - DB_URL='jdbc:postgresql://postgres:5432/postgresql?ssl=allow'
      # - DB_USERNAME=keycloak
      # - DB_PASSWORD=secret
      # - KEYCLOAK_ADMIN=admin
      # - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=secret
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    networks:
      # proxy:
      keycloak:
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.keycloak.entrypoints=http"
    #   - "traefik.http.routers.keycloak.rule=Host(`keycloak.yourdomain.com`)"
    #   - "traefik.http.middlewares.keycloak-https-redirect.redirectscheme.scheme=https"
    #   - "traefik.http.routers.keycloak.middlewares=keycloak-https-redirect"
    #   - "traefik.http.routers.keycloak-secure.entrypoints=https"
    #   - "traefik.http.routers.keycloak-secure.rule=Host(`keycloak.yourdomain.com`)"
    #   - "traefik.http.routers.keycloak-secure.tls=true"
    #   - "traefik.http.routers.keycloak-secure.service=keycloak"
    #   - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    #   - "traefik.docker.network=proxy"
    ports:
      - 8080:8080
      - 8443:8443

networks:
  # proxy:
  #   external: true
  keycloak:
